import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <nav
          style={{
            display: "flex",
            gap: "20px",
            padding: "20px",
            background: "#eee",
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/services">Services</Link>
        </nav>

        <main>{children}</main>
        <footer
          style={{
            marginTop: "40px",
            padding: "20px",
            background: "#ddd",
            textAlign: "center",
          }}
        >
          © 2026 My Next App
        </footer>
      </body>
    </html>
  );
}
